### ISSUE TITLE
Emoticon to differentiate idea (memos plugin) and event (big calendar plugin)

### ISSUE THREAD

**Issue by javiavid** [Quorafind/Obsidian-Big-Calendar#17]
An optional configuration can be interesting to differentiate ideas and events.
For example, putting 💡 before an idea and 📅 before an event.

![image](https://user-images.githubusercontent.com/7627504/148352827-f856bfff-ff8e-42e6-af5c-77e7fcf8f4eb.png)

**Comment by Quorafind** [comment]
Yes, you can do it right now by adding css, I will push an update to let you choose which emoji you want before the specific journal

**Comment by Quorafind** [comment]
like, you can use this now: 
```css
.rbc-event.TODO {
    background-color: #660066
}

.rbc-event.TODO .rbc-event-content::before {
    content: "📮 "
}

.rbc-event.DONE {
    background-color: #006600
}

.rbc-event.DONE .rbc-event-content::before {
    content: "✅ "
}

.rbc-event.JOURNAL {
    background-color: #7A7A7A
}

.rbc-event.JOURNAL .rbc-event-content::before {
    content: "📅 "
}
```
